service: subscriptionList
provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, 'local'}
  region: ${opt:region, 'us-east-1'} 
  environment:
    ENV: ${opt:stage, 'local'}
    REGION: ${self:provider.region}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - "dynamodb:*"
      Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/*"

plugins:
  - serverless-offline

custom:
  serverless-offline:
    port: 4000

functions:
  list:
    handler: handler.list
    events:
      - http:
          path: subscriptionList
          method: get
          cors: true
          authorizer: 
            arn: ${ssm:AUTHORIZER_ARN~true}

  update:
    handler: handler.update
    events:
      - http:
          path: subscriptionList
          method: put
          cors: true
          authorizer: 
            arn: ${ssm:AUTHORIZER_ARN~true}

  delete:
    handler: handler.del
    events:
      - http:
          path: subscriptionList
          method: delete
          cors: true
          authorizer: 
            arn: ${ssm:AUTHORIZER_ARN~true}