service: authorizer

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, 'local'}
  region: ${opt:region, 'us-east-1'} 
  environment:
    ENV: ${opt:stage, 'local'}
    REGION: ${self:provider.region}
    JWT_SECRET: ${ssm:JWT_SECRET~true}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - "dynamodb:*"
      Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/*"

functions:
  authorize:
    handler: handler.authorize
