service: topics

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, 'local'}
  region: ${opt:region, 'us-east-1'} 
  environment:
    ENV: ${opt:stage, 'local'}
    REGION: ${self:provider.region}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - "dynamodb:*"
      Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/*"

functions:

  list:
    handler: handler.list
    events:
      - http:
          path: topics
          method: get
          cors: true

  update:
    handler: handler.update
    events:
      - http:
          path: topics
          method: put
          cors: true

  delete:
    handler: handler.del
    events:
      - http:
          path: topics
          method: delete
          cors: true

