service: subTopicList

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, 'local'}
  region: ${opt:region, 'us-east-1'} 
  environment:
    ENV: ${opt:stage, 'local'}
    REGION: ${self:provider.region}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - "dynamodb:*"
      Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/*"

plugins:
  - serverless-offline

custom:
  serverless-offline:
    port: 4000
    debug: false

functions:
  list:
    handler: handler.list
    events:
      - http:
          path: subTopicList
          method: get
          cors: true
