# Service name
service: article


provider:
  name: aws
  runtime: nodejs8.10
  region: us-east-1
  environment:
    LISTEN_SERVER: ${ssm:listen_server~true}
    LISTEN_JWT: ${ssm:listen_jwt~true}
  iamRoleStatements:
  - Effect: Allow
    Action:
      - "dynamodb:*"
    Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/*"
           
functions:
  article:
    handler: handler.article
    events:
      - http:
          path: article
          method: post
          cors: true
