service: login

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, 'local'}
  region: ${opt:region, 'us-east-1'} 
  environment:
    ENV: ${opt:stage, 'local'}
    REGION: ${self:provider.region}
    JWT_SECRET: ${ssm:JWT_SECRET~true}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - "dynamodb:*"
      Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/*"

plugins:
  - serverless-offline

custom:
  serverless-offline:
    port: 4001

functions:
  login:
    handler: handler.login
    events:
      - http:
          path: login
          method: post
          cors: true
